name: Python Package

on:
  pull_request:
  push:
    branches:
      - main
      - stable
    tags:
      - 'v*.*.*'

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        include:
#          - os: 'ubuntu-latest'
#            python: '3.10'
#            name: 'Linux'
#
#          - os: 'macos-latest'
#            python: '3.10'
#            name: 'macOS'

          - os: 'windows-latest'
            python: '3.10'
            name: 'Windows'


    runs-on: ${{ matrix.os }}

    name: ${{ matrix.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: ${{ matrix.python }}

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Set up cache
        uses: actions/cache@v2.1.7
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python packages
        run: |
          python -m pip install --upgrade -r requirements-setuptools.txt
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-pyinstaller.txt

      - name: create executable
        run: |
          python -m PyInstaller dread_editor.spec
          cd dist
          7z a -mx=7 -myx=7 dread_editor_${{ matrix.name }}.7z dread_editor

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Dread Editor ${{ matrix.name }}
          if-no-files-found: error
          path: |
            dist/dread_editor_${{ matrix.name }}.7z

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.2.1
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/dread_editor_${{ matrix.name }}.7z
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
          body: "Release executable"
